initial current location sent and received from wamp server completed
xconn-projects/location-tracker pull request #1
Opened 2024-07-06 13:18 UTC by shakeebkhan66

2024-07-11 08:08 UTC, muzzammilshahid requested changes

2024-07-11 08:08 UTC, muzzammilshahid commented on lib/model/latlong_model.dart
> +import "dart:convert";
We are not using this file?

2024-07-11 08:08 UTC, muzzammilshahid commented on lib/res/wamp_util.dart
> +import "package:location_tracker/res/constants.dart";
This file is not needed. Now we have static data, and this can be simplified.

2024-07-11 08:08 UTC, muzzammilshahid commented on lib/res/constants.dart
> +const msgPackSerializer = "MsgPack";
```suggestion
/// Serializers ///
```

2024-07-11 10:48 UTC, asimfarooq5 requested changes

2024-07-11 10:48 UTC, asimfarooq5 commented on lib/controllers/live_location_cont.dart
> +    deviceName = (await plugin.getName())!;
Add null check for safety: 
deviceName = await plugin.getName() ?? "Unknown Device";

2024-07-11 10:48 UTC, asimfarooq5 commented on lib/controllers/live_location_cont.dart
> +    await _publish(30.19182, 71.44313, deviceName);
Avoid hardcoding coordinates.

2024-07-11 10:49 UTC, asimfarooq5 requested changes

2024-07-11 10:49 UTC, asimfarooq5 commented on lib/controllers/live_location_cont.dart
> +    print("hello");
Remove debug code.

2024-07-13 14:57 UTC, asimfarooq5 approved these changes

2024-07-15 09:02 UTC, muzzammilshahid requested changes

2024-07-15 11:53 UTC, muzzammilshahid approved these changes

2024-07-15 11:57 UTC, merged